require:
  - 'rubocop-rails'
  - 'rubocop-performance'

AllCops:
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'db/migrate/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 26

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Style/Documentation:
  Enabled: false
