inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

