name: lint
# Controls when the workflow will run:
on:
  # Triggers the workflow on push to master branch, or on pull request
  # to any branch:
  push:
    branches:
      - master
  pull_request:

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linters
        run: |
          bundle exec rubocop --parallel
